### ISSUE TITLE
Installing add on does not do anything.

### ISSUE THREAD

**Issue by SiHaag** [Arthur-Milchior/anki-Multiple-Windows#7]
I would love to use this great add on but can't as I don't know how do I use it. I thought clicking on add would do something but it didn't and is normal just like before. I am on Anki 2.1.33.

**Comment by SiHaag** [comment]
> I would love to use this great add on but can't as I don't know how do I use it. I thought clicking on add would do something but it didn't and is normal just like before. I am on Anki 2.1.33.

I'm sorry its working if I minimize the window first. Thanks a lot for the great add on!!

**Comment by Arthur-Milchior** [comment]
No trouble. this add-on does not control window size
