### ISSUE TITLE
requireReset() got an unexpected keyword argument 'reason'

### ISSUE THREAD

**Issue by galantra** [Arthur-Milchior/anki-Multiple-Windows#8]
I upgraded to Anki 2.1.35, updated updatable add-ons, and now I get this error when trying to open an edit (not add) window:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-25 06:16:22

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1068, in onEditCurrent
  File "C:\Users\emanresu\PortableApps\AnkiPortable\Anki2\addons21\354407385\__init__.py", line 53, in open
    return function(name, *args, **kwargs)
  File "C:\Users\emanresu\PortableApps\AnkiPortable\Anki2\addons21\354407385\__init__.py", line 65, in openMany
    instance = creator(*args, **kwargs)
  File "<C:\Users\emanresu\PortableApps\AnkiPortable\Anki\decorator.pyc:decorator-gen-26>", line 2, in __init__
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 629, in repl
  File "aqt\editcurrent.py", line 31, in __init__
TypeError: requireReset() got an unexpected keyword argument 'reason'

```

Is it related to what you wrote in the readme?

> aqt.editcurrent's method EditCurrent.onReset is redefined. Thus this add-on may be incompatible with other add-on changing this.
I use [copy note contents to new Add window (from Browser, Reviewer, Add, EditCurrent)](https://ankiweb.net/shared/info/759018284) and [Keep model of add cards](https://ankiweb.net/shared/info/424778276), among other add-ons.

I'm writing to ask if you think (based on the error message) that add-on interference is improbable. If it's probable, I will test add-on compatibility.

**Comment by galantra** [comment]
Nevermind. The error also occurs when the add-on is disabled (I thought I had started Anki with the add-on disabled, but nevertheless I found out that it was still enabled after restart. After 2 or 3 times it worked. Probably this was a misperception or error on my part).

**Comment by Arthur-Milchior** [comment]
If it occurs with the add-on disabled, you should report it on https://forums.ankiweb.net/ if it's not already done. 
Thanks for taking the time to read the readme, make a specific bug request, and updating with relevant update. Even if I can't help more, it's still appreciated
